### ISSUE TITLE
Hoverboard Hack 

### ISSUE THREAD

**Issue by Tirta01** [LeoDJ/IoT-in-the-box#1]
Hi, sorry to have asked on this page, I'm a new user in github and dont know how to ask. I am interested in your project about Hoverboard hack. Before, i tried to make [openchair project](https://hackaday.io/project/13347-openchair) from hackaday.io, it uses nucleo F446RE to control mainboard, but I cant get it to work with some warning messages when flashing the firmware. my question

1. What is the IDE program to flash firmware to mainboard?
2. How to make original firmware backups of the mainboard, before uploading a new one. Any other limitations for considering?
3. The chip on mainboard of my hoverboard is GD32F103RCT6, any issue about incompatablility?

It helps me a lot with decision how to proceed further. Many thanks for your reply and help.

**Comment by LeoDJ** [comment]
I'm sorry, I didn't notice that issues were disabled on the fork. Would you kindly copy your issue to the correct repository? I will answer you there then.
